modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="more_coals"
version="1.3.3"
displayName="More Coals"
credits="https://www.mcmod.cn/class/3733.html"
displayURL="https://www.mcmod.cn/class/3733.html"
authors="»¯Áú·ÙÌì"
description='''
Coals Expand
'''

[[dependencies.more_coals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




